spring.application.name=demo
# Nome e Conexão do Banco de Dados H2 na memória
spring.datasource.url=jdbc:h2:mem:chamadosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA / Hibernate para criar e atualizar as tabelas sozinho
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o console web do H2 (para você testar e visualizar no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console